[versions]
androidx-core = "1.12.0"
androidx-appcompat = "1.6.1"
material = "1.10.0"

compose-bom = "2024.02.00"
activity-compose = "1.9.0"
kotlin = "1.9.24"

junit = "4.13.2"
androidx-junit = "1.1.5"
espresso = "3.5.1"

agp = "8.2.2"
composeCompiler = "1.5.14"

# Compose plugin
kotlin-compose = "2.0.0"
firebase-firestore = "26.0.2"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }

# Compose using BOM
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }

# Activity Compose
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebase-firestore" }

[plugins]
android-application = { id = "com.android.application", version = "8.2.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-compose" }


